### ISSUE TITLE
Crash when open (using on the server)

### ISSUE THREAD

**Issue by VannaKarenina** [McJtyMods/HoloGui#2]
Here is a crash log : https://pastebin.com/r0iekPgF

**Comment by McJty** [comment]
I will check it out

**Comment by VannaKarenina** [comment]
After auto restart, the server does not start with a core error

**Comment by McJty** [comment]
Oh, this has been fixed a long time ago. You're using a very old version of hologui

**Comment by VannaKarenina** [comment]
I will check it
