### ISSUE TITLE
right clicking on the portal block take you to Ariente dimension crashes game

### ISSUE THREAD

**Issue by CitiesXL2815** [McJtyMods/HoloGui#4]
when the UI pops up it crashes the game and trying to restart after the crash, crashes again when world loads up

=====================================================

MC version: 1.12.2
Ariente and world Version: 0.0.22-alpha
HoloGui version: 0.0.8-beta
mcjtylib version: 3.5.2
Forge Version: 2838
Optifine: no

=====================================================

Crash log: https://gist.github.com/CitiesXL2815/12f5eb4b789cb565c8fd20f46651ce3b

**Comment by McJty** [comment]
I will fix this

**Comment by CitiesXL2815** [comment]
thx
